### ISSUE TITLE
Update doesn’t seem to respect release type

### ISSUE THREAD

**Issue by therobbiedavis** [bigshit11elf/kavitaupdater#1]
https://github.com/bigshit11elf/kavitaupdater/blob/f0da2900dd570e13d9dd275a2b4a127e0817aa95/kupdate.sh#L249

This line seems to only extract the x64 version however if the user were to select arm as the release type I think it would fail due to being hard coded.

**Comment by bigshit11elf** [comment]
You're correct. Updated it with the correct variable so that user choice is respected. So: resolved?!
